# 端口
server:
  port: 8000
# 数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/mall_order
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 987654
# mapper.xml扫描
mybatis-plus:
  mapper-locations: classpath:mapper/**/.*xml
  global-config:
    db-config:
      id-type: auto