# 端口
server:
  port: 7000
# 数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/mall_member
    username: root
    password: 987654
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# mapper.xml扫描
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto